steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - 'SECRET_KEY=$_SECRET_KEY'
      - 'DATABASE_URL=$_DATABASE_URL'
    args:
      ["build",
      "--build-arg=SECRET_KEY=${SECRET_KEY}",
      "--build-arg=DATABASE_URL=${DATABASE_URL}", 
      "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]
   

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]