steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "gunicorn",
        "--bind","8080",
        "--workers", "1",
        "--worker-class", "uvicorn.workers.UvicornWorker",
        "--threads","8", 
        "app.main:app" ,
      ]